export const bikes = [
  {
    id: "Trek Marlin 7w",
    name: "Trek Marlin 7",
    description:
      "The Marlin 7 is your best friend on the trail and wherever else you roll thanks to its confidence-boosting trail geometry. It finds the perfect balance between price and performance with an upgraded RockShox suspension fork that makes quick work of rocks and bumps in your path and the huge gearing range of a SRAM 12-speed SX Eagle drivetrain.",
    img: "../src/data/marlin-7-resize.jpg",
    price: `1000$`,
    colors: "white",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
  {
    id: "Trek Procaliber 8gray",
    name: "Trek Procaliber 8",
    description: `The Procaliber 8 is a cross-country mountain bike built for hot laps and singletrack. It confidently rolls the fine line between race-ready and pocket-friendly with an alloy frame that's built with modern geometry for handling fast corners and rough sections of trail while keeping you ready to sprint up climbs. A 12-speed Shimano SLX and XT drivetrain and 120 mm RockShox Recon Gold fork seal the deal with all the gears and rock-smoothing comfort you need.`,
    img: "../src/data/procalibre-resize.jpg",
    price: `1199$`,
    colors: "green-gray",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
  {
    id: "red",
    name: "Merida BIG.SEVEN 200",
    description:
      'Single chainring aluminium 27.5" wheeled hardtail, featuring a 100 mm air suspension fork, a 10-speed Shimano drivetrain and powerful hydraulic disc brakes. The BIG.SEVEN 200 is ready for your next off-road adventure. ',
    img: "../src/data/big-seven-200-resize.jpg",
    price: `899$`,
    colors: "dark-strawberry",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
  {
    id: "Merida BIG.NINE 9000blue",
    name: "Merida BIG.NINE 9000",
    description: `Our lightest BIG.NINE ever. Super light CF5 carbon frame on top components. We've left no stone unturned to make sure this bike is ready to race right out of the box.`,
    img: "../src/data/big-nine-resize.jpg",
    price: `7000$`,
    colors: "light-blue",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
  {
    id: "Epic Hardtail Comp123",
    name: "Epic Hardtail Comp",
    description: `Gone are the days where a date with a hardtail race bike meant paying for it for days to come. Now, the Epic Hardtail Comp’s reality-altering combination of comfort and capability in a lighter-than-life package means counting down the hours until you meet again.`,
    img: "../src/data/specialized-epic-resize.jpg",
    price: `2699$`,
    colors: "mettalic-gold",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
  {
    id: "Chisel Hardtail Compredwhite",
    name: "Chisel Hardtail Comp",
    description: `Gone are the days where a date with a hardtail race bike meant paying for it for days to come. Now, the Epic Hardtail Comp’s reality-altering combination of comfort and capability in a lighter-than-life package means counting down the hours until you meet again.`,
    img: "../src/data/specialized-chisel-resize.jpg",
    price: `2699$`,
    colors: "dark-red-white",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },

  {
    id: "Trek Marlin 7",
    name: "Trek Marlin 7",
    description:
      "The Marlin 7 is your best friend on the trail and wherever else you roll thanks to its confidence-boosting trail geometry. It finds the perfect balance between price and performance with an upgraded RockShox suspension fork that makes quick work of rocks and bumps in your path and the huge gearing range of a SRAM 12-speed SX Eagle drivetrain.",
    img: "../src/data/marlin-7-resize.jpg",
    price: `1000$`,
    colors: "white",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
  {
    id: "Trek Procaliber 8",
    name: "Trek Procaliber 8",
    description: `The Procaliber 8 is a cross-country mountain bike built for hot laps and singletrack. It confidently rolls the fine line between race-ready and pocket-friendly with an alloy frame that's built with modern geometry for handling fast corners and rough sections of trail while keeping you ready to sprint up climbs. A 12-speed Shimano SLX and XT drivetrain and 120 mm RockShox Recon Gold fork seal the deal with all the gears and rock-smoothing comfort you need.`,
    img: "../src/data/procalibre-resize.jpg",
    price: `1199$`,
    colors: "green-gray",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
  {
    id: "Trek Procalibe222r 8",
    name: "Trek Procaliber 8",
    description: `The Procaliber 8 is a cross-country mountain bike built for hot laps and singletrack. It confidently rolls the fine line between race-ready and pocket-friendly with an alloy frame that's built with modern geometry for handling fast corners and rough sections of trail while keeping you ready to sprint up climbs. A 12-speed Shimano SLX and XT drivetrain and 120 mm RockShox Recon Gold fork seal the deal with all the gears and rock-smoothing comfort you need.`,
    img: "../src/data/procalibre-resize.jpg",
    price: `1199$`,
    colors: "green-gray",
    size: ["s", "m", "l", "xl", "xxl"],
    specs: null,
  },
];
